# -*- coding: utf-8 -*-
"""AI-Agent-Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnBolq2J-NTcrzH8EmXLogySUQu7T2Xk
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Sales Data')