# -*- coding: utf-8 -*-
"""AI-Agent-Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnBolq2J-NTcrzH8EmXLogySUQu7T2Xk
"""

from google.colab import files
files.download("requirements.txt")

requirements = """
streamlit
pandas
numpy
plotly
"""
with open("requirements.txt", "w") as f:
    f.write(requirements.strip())