# -*- coding: utf-8 -*-
"""AI-Agent-Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnBolq2J-NTcrzH8EmXLogySUQu7T2Xk
"""

import streamlit as st
import pandas as pd
import numpy as np

#set up the app page
st.title('Sales Data')



#import the dataframe
uploaded_file = st.file_uploader('Choose a .csv file')
if uploaded_file is not None:
#read csv
df = pd.read_csv(uploaded_file)

