# -*- coding: utf-8 -*-
"""AI-Agent-Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnBolq2J-NTcrzH8EmXLogySUQu7T2Xk
"""
import plotly.express as px
import streamlit as st
import pandas as pd
import numpy as np

#set up the app page
st.set_page_config('InsightBot: Sales Data Assistant', layout='wide')
st.title('InsightBot: Sales Data Assistant')

tab1, tab2, tab3, tab4, tab5 = st.tabs(['Upload & Overview', 'Insights', 'Visualizations','Smart Assistant', 'Export'])

with tab1:
    st.header('Upload your Data File (CSV)')
    st.image('https://cdn.prod.website-files.com/6064b31ff49a2d31e0493af1/6811f5efb2d08280bdf50863_63ff784daa460f472e688fb0_csv%2520(2).png', width=200)
    #import the dataframe
    uploaded_file = st.file_uploader('Choose a .csv file')
    if uploaded_file is not None:
      #read csv
      df = pd.read_csv(uploaded_file)
      st.session_state["data"] = df
      st.dataframe(df, height=1500)
    else:
      st.warning('You need to upload a CSV file.')
with tab2:
    st.header("Gain Data Insights")
    st.image('https://www.dimensions.ai/wp-content/uploads/2023/02/corporateRD-220324-usecase-image-02.png', width=200)

    if "data" in st.session_state:
        df = st.session_state["data"]

        # Layout metrics in columns
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Sales", f"${df['Sales_Amount'].sum():,.2f}")
        col2.metric("Avg. Order Value", f"${df['Sales_Amount'].mean():.2f}")
        col3.metric("Top Region", df["Region"].value_counts().idxmax())

        # Filter dropdown
        selected_category = st.selectbox("Choose a product category", df["Product_Category"].unique())

        # Display summary
        filtered_df = df[df["Product_Category"] == selected_category]
        st.write(f"Total sales for {selected_category}: ${filtered_df['Sales_Amount'].sum():,.2f}")

        # Chart
        region_order = ["North", "East", "South", "West"]
        filtered_df["Region"] = pd.Categorical(filtered_df["Region"], categories=region_order, ordered=True)

        fig = px.bar(filtered_df, x="Region", y="Sales_Amount", title=f"{selected_category} Sales by Region")

        st.plotly_chart(fig, use_container_width=True)

    else:
        st.warning("Please upload a CSV file first in the 'Upload' tab.")

with tab3:
    st.header('Visualize Your Data')
    st.image('https://images.ctfassets.net/pdf29us7flmy/1OY6V5qnB5e490hm3lTK2i/c490cc85b117b64bc5ac10f0b9d6f1a4/GOLD-6487-CareerGuide-Batch04-Images-GraphCharts-04-Histogram.png?w=720&q=100&fm=jpg', width=200)
with tab4:
    st.header('Chat with a Smart Asisstant')
    st.image('https://litslink.com/wp-content/uploads/2023/11/f2-1.png', width=400)
with tab5:
    st.header('Save and Export')
    st.image('https://static-00.iconduck.com/assets.00/save-icon-512x512-552twxqx.png', width=200)
